###################################################
# Batch running of events
###################################################

# verbosity
/tracking/verbose 0
/control/verbose 0
/run/verbose 0

/run/numberOfThreads 1
/run/initialize

/RunAction/output/file AlphaTest.root

# GPS Particle Generation
/gps/particle alpha
/gps/pos/type Point
/gps/pos/centre -314 72 290
/gps/ang/type iso
/gps/energy 5.4 MeV
/gps/position -314 72 290

/run/beamOn 10

/gps/particle alpha
/gps/pos/type Point
/gps/pos/centre -314 72 290
/gps/ang/type iso
/gps/energy 100 MeV
/gps/position -314 72 290

/run/beamOn 10