###################################################
# Batch running of events  
###################################################
# Macro for running dune10kt_v6_refactored.
# verbosity
/tracking/verbose 0
/control/verbose 0
/run/verbose 0
# can be csv, root or hdf5
#/RunAction/output/file dune10kt_v6_refactored.root
/RunAction/output/file test.root
# GPS Particle Generation

/gps/particle e-
/gps/energy 3 GeV
/gps/direction 0 0 -1
#/gps/position 0 0 0
/gps/position 200 300 1000
/run/beamOn 1