###################################################
# Batch running of events  
###################################################

# verbosity
/tracking/verbose 0
/control/verbose 0
/run/verbose 0
# can be csv, root or hdf5
/RunAction/output/file out.root

# GPS Particle Generation
/gps/particle mu-
/gps/energy 3 GeV
/gps/direction 0 0 -1
/gps/position 0 500 0
#/gps/position 200 300 1000
/run/beamOn 1