###################################################
# Batch running of events
###################################################

# verbosity
/tracking/verbose 0
/control/verbose 0
/run/verbose 0
/run/numberOfThreads 1
/run/initialize
# Enable or disable (True/False) scintillation and Cherenkov optical photon propagation in Geant4.
#/process/optical/scintillation/setStackPhotons false
#/process/optical/cerenkov/setStackPhotons false
/RunAction/output/file out.root

# GPS Particle Generation
/gps/particle e-
/gps/pos/type Point
/gps/pos/centre 0 200 650
/gps/ang/type iso
/gps/energy 3 GeV
/gps/position 0 200 650



/run/beamOn 1
