###################################################
# Batch running of events  
###################################################

# verbosity
/tracking/verbose 0
/control/verbose 0
/run/verbose 0

/run/numberOfThreads 1
/run/initialize

# can be csv, root or hdf5
/RunAction/output/file Performance_G4_profiling.root

# PrimaryGenerationAction
/PrimaryGenerationAction/input/type Performance # GPS, Performance, or use ROOT


/PrimaryGenerationAction/input/pos 175 0 695 # Performance # GPS, Performance, or use ROOT

# Produce scintilation photons with a gaussian distribution.
/PrimaryGenerationAction/input/momentum 9.7 eV  ## The mean momentum of Scintilation Photons.
/PrimaryGenerationAction/input/sigma_momentum 0.1 eV  ## sigma value for the momentum .

/PrimaryGenerationAction/input/repeats 1  ## How many times to repeat the same event (for performance testing)
/PrimaryGenerationAction/input/PhLinAmount 0.25 25 15  ## linearly spaced energies from 0.25 to 25 MeV, 11 points.
/run/beamOn 15 # Number of total events to run. Should be repeats * number of energies. As an example, 2 repeats * 11 energies = 22 events.
