###################################################
# Batch running of events  
###################################################

# verbosity
/tracking/verbose 0
/control/verbose 0
/run/verbose 0
# can be csv, root or hdf5
/RunAction/output/file voxelTest.root

# PrimaryGenerationAction
/PrimaryGenerationAction/input/type ROOT # GPS or use ROOT
/PrimaryGenerationAction/input/file test.root
/run/beamOn 1000